$:
  vscode:
    - docker:
        build: .ide/Dockerfile
        #image: mcr.microsoft.com/devcontainers/universal
        #image: mcr.microsoft.com/devcontainers/go:1.24
      services:
        - vscode
        - docker

feat*:
  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/spencezhang/my-keys/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/logzh/${CNB_REPO_NAME}.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
